import {
  IL_LIGA_GERMANY,
  IL_LIGA_INGGRIS,
  IL_LIGA_ITALY,
  IMGJersey_Chelsea1,
  IMGJersey_Chelsea2,
  IMGJersey_Dortmund1,
  IMGJersey_Dortmund2,
  IMGJersey_Liverpool1,
  IMGJersey_Liverpool2,
  IMGJersey_Milan1,
  IMGJersey_Milan2,
} from '../..';

export const DummiesOrders = [
  {
    id: 1,
    tanggalPemesanan: 'Kamis, 17 September 2020',
    status: 'keranjang',
    totalHarga: 500000,
    berat: 1,
    pesanans: [
      {
        id: 1,
        product: {
          id: 1,
          nama: 'CHELSEA 3RD 2018-2019',
          gambar: [IMGJersey_Chelsea1, IMGJersey_Chelsea2],
          liga: {
            id: 2,
            nama: 'Premier League',
            gambar: IL_LIGA_INGGRIS,
          },
          harga: 125000,
          berat: 0.25,
          jenis: 'Replika Top Quality',
          ukuran: ['S', 'M', 'L', 'XL', 'XXL'],
          ready: true,
        },
        jumlahPesan: 1,
        totalHarga: 125000,
        keterangan: null,
        ukuran: 'L',
      },
      {
        id: 2,
        product: {
          id: 2,
          nama: 'DORTMUND AWAY 2018-2019',
          gambar: [IMGJersey_Dortmund1, IMGJersey_Dortmund2],
          liga: {
            id: 4,
            nama: 'Bundesliga',
            gambar: IL_LIGA_GERMANY,
          },
          harga: 125000,
          berat: 0.25,
          jenis: 'Replika Top Quality',
          ukuran: ['S', 'M', 'L', 'XL', 'XXL'],
          ready: true,
        },
        jumlahPesan: 3,
        totalHarga: 375000,
        keterangan: null,
        ukuran: 'L',
      },
    ],
  },
  {
    id: 2,
    tanggalPemesanan: 'Jumat, 18 September 2020',
    status: 'lunas',
    totalHarga: 375000,
    berat: 0.75,
    pesanans: [
      {
        id: 1,
        product: {
          id: 5,
          nama: 'LIVERPOOL AWAY 2018-2019',
          gambar: [IMGJersey_Liverpool1, IMGJersey_Liverpool2],
          liga: {
            id: 2,
            nama: 'Premier League',
            gambar: IL_LIGA_INGGRIS,
          },
          harga: 125000,
          berat: 0.25,
          jenis: 'Replika Top Quality',
          ukuran: ['S', 'M', 'L', 'XL', 'XXL'],
          ready: true,
        },
        jumlahPesan: 1,
        totalHarga: 125000,
        keterangan: 'Nama Jersey : Eko Nomor Punggung : 9.',
        ukuran: 'L',
      },
      {
        id: 2,
        product: {
          id: 7,
          nama: 'AC MILAN HOME 2018 2019',
          gambar: [IMGJersey_Milan1, IMGJersey_Milan2],
          liga: {
            id: 3,
            nama: 'Serie A',
            gambar: IL_LIGA_ITALY,
          },
          harga: 125000,
          berat: 0.25,
          jenis: 'Replika Top Quality',
          ukuran: ['S', 'M', 'L', 'XL', 'XXL'],
          ready: true,
        },
        jumlahPesan: 2,
        totalHarga: 255000,
        keterangan: 'Nama Jersey : Afif Nomor Punggung : 10.',
        ukuran: 'M',
      },
    ],
  },
];
