import {
  IL_LIGA_GERMANY,
  IL_LIGA_INGGRIS,
  IL_LIGA_ITALY,
  IL_LIGA_SPANYOL,
  IMGJersey_Chelsea1,
  IMGJersey_Chelsea2,
  IMGJersey_Dortmund1,
  IMGJersey_Dortmund2,
  IMGJersey_Juve1,
  IMGJersey_Juve2,
  IMGJersey_Leicester1,
  IMGJersey_Leicester2,
  IMGJersey_Liverpool1,
  IMGJersey_Liverpool2,
  IMGJersey_Madrid1,
  IMGJersey_Madrid2,
  IMGJersey_Milan1,
  IMGJersey_Milan2,
  IMGJersey_Munchen1,
  IMGJersey_Munchen2,
} from '../..';

export const DummiesJersey = [
  {
    id: 1,
    name: 'Chelsea 3rd 2018/2019',
    image: [IMGJersey_Chelsea1, IMGJersey_Chelsea2],
    liga: {
      id: 2,
      name: 'Premier League',
      image: IL_LIGA_INGGRIS,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 2,
    name: 'Dortmund Away 2018/2019',
    image: [IMGJersey_Dortmund1, IMGJersey_Dortmund2],
    liga: {
      id: 3,
      name: 'Bundesliga',
      image: IL_LIGA_GERMANY,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 3,
    name: 'Juventus 3rd 2018/2019',
    image: [IMGJersey_Juve1, IMGJersey_Juve2],
    liga: {
      id: 4,
      name: 'Serie A',
      image: IL_LIGA_ITALY,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 4,
    name: 'Real Madrid 3rd 2018/2019',
    image: [IMGJersey_Madrid1, IMGJersey_Madrid2],
    liga: {
      id: 1,
      name: 'La Liga',
      image: IL_LIGA_SPANYOL,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 5,
    name: 'Milan Home 2018/2019',
    image: [IMGJersey_Milan1, IMGJersey_Milan2],
    liga: {
      id: 4,
      name: 'Serie A',
      image: IL_LIGA_ITALY,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 6,
    name: 'Munchen 3rd 2018/2019',
    image: [IMGJersey_Munchen1, IMGJersey_Munchen2],
    liga: {
      id: 3,
      name: 'Bundesliga',
      image: IL_LIGA_GERMANY,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 7,
    name: 'Leichester Home 2018/2019',
    image: [IMGJersey_Leicester1, IMGJersey_Leicester2],
    liga: {
      id: 2,
      name: 'Premier League',
      image: IL_LIGA_INGGRIS,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
  {
    id: 7,
    name: 'Liverpool 3rd 2018/2019',
    image: [IMGJersey_Liverpool1, IMGJersey_Liverpool2],
    liga: {
      id: 2,
      name: 'Premier League',
      image: IL_LIGA_INGGRIS,
    },
    harga: 125000,
    berat: 0.25,
    jenis: 'Replika Top Quality',
    ukuran: ['S', 'M', 'L', 'XL'],
    ready: true,
  },
];
