// user
export const GET_USER = 'GET_USER';

// Raja Ongkir
export const GET_PROVINCE_REQUEST = 'GET_PROVINCE_REQUEST';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAILED = 'GET_PROVINCE_FAILED';

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAILED = 'GET_CITY_FAILED';

// General
export const SHOW_LOADING = 'SHOW_LOADING';

// AUTH
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILED = 'AUTH_REGISTER_FAILED';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

// PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

// LIGA
export const GET_LIGA_REQUEST = 'GET_LIGA_REQUEST';
export const GET_LIGA_SUCCESS = 'GET_LIGA_SUCCESS';
export const GET_LIGA_FAILED = 'GET_LIGA_FAILED';

// JERSEY
export const GET_JERSEY_REQUEST = 'GET_JERSEY_REQUEST';
export const GET_JERSEY_SUCCESS = 'GET_JERSEY_SUCCESS';
export const GET_JERSEY_FAILED = 'GET_JERSEY_FAILED';

// JERSEY BY LIGA
export const GET_JERSEY_BY_LIGA = 'GET_JERSEY_BY_LIGA';
export const DELETE_STATE_JERSEY_BY_LIGA = 'DELETE_STATE_JERSEY_BY_LIGA';

// SEARCH
export const SAVE_KEYWORD_JERSEY = 'SAVE_KEYWORD_JERSEY';

// CART
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const GET_CART_LIST_REQUEST = 'GET_CART_LIST_REQUEST';
export const GET_CART_LIST_SUCCESS = 'GET_CART_LIST_SUCCESS';
export const GET_CART_LIST_FAILED = 'GET_CART_LIST_FAILED';

export const DELETE_CART_ITEM_REQUEST = 'DELETE_CART_ITEM_REQUEST';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED';
